default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

## Development and test will pull the info from default to make use of your local postgres server
development:
  <<: *default
  database: blog_backend_development
  username: test1
  password: test1
  port: 5432
  host: localhost

test:
  <<: *default
  database: blog_backend_test
  username: test1
  password: test1
  port: 5432
  host: localhost

## If you plan on deploying to Heroku, the setup below will make sure when you deploy to heroku it will be pointing to your heroku database.
production:
  <<: *default
  database: blog_backend_production
  # url: <%= ENV['DATABASE_URL'] %>
  url: <%= ENV['postgres://sibgeunpnfrgmi:8580222e911e25f27f77be1b6e6086af1659a23e33fa47bd2d2e4ba01b5f1e2c@ec2-54-196-1-212.compute-1.amazonaws.com:5432/d3ecla3q023pem'] %>
