default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

## Development and test will pull the info from default to make use of your local postgres server
development:
  <<: *default
  database: blog_backend_development
  username: test1
  password: test1
  port: 5432
  host: localhost

test:
  <<: *default
  database: blog_backend_test
  username: test1
  password: test1
  port: 5432
  host: localhost

## If you plan on deploying to Heroku, the setup below will make sure when you deploy to heroku it will be pointing to your heroku database.
production:
  <<: *default
  database: blog_backend_production
  url: <%= ENV['DATABASE_URL'] %>
